apiVersion: sagemaker.aws.amazon.com/v1
kind: TrainingJob
metadata:
  name: d2-coco2017-training # add unique job name
spec:
    hyperParameters:
        - name: config-file
          value: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
        - name: opts
          value: "SOLVER.BASE_LR 0.00025 MODEL.ROI_HEADS.NUM_CLASSES 80 DATALOADER.NUM_WORKERS 2"
    algorithmSpecification:
        trainingImage: <AWS account>.dkr.ecr.<AWS region>.amazonaws.com/<your_container_name> # add your image URI
        trainingInputMode: File
        metricDefinitions:
        - name: "total_loss"
          regex: ".*total_loss:/\/s([0-9\\.]+)/\/s*"
        - name: "loss_cls"
          regex: ".*loss_cls:/\/s([0-9\\.]+)/\/s*"
        - name: "loss_box_reg"
          regex: ".*loss_box_reg:/\/s([0-9\\.]+)/\/s*"
        - name: "loss_mask"
          regex: ".*loss_mask:/\/s([0-9\\.]+)/\/s*"
        - name: "loss_rpn_cls"
          regex: ".*loss_rpn_cls:/\/s([0-9\\.]+)/\/s*"          
        - name: "loss_rpn_loc"
          regex: ".*loss_rpn_loc:/\/s([0-9\\.]+)/\/s*"       
    roleArn: <Sagemaker Role ARN> # add your Sagemaker execution role
    region: <AWS Region> # add your region
    outputDataConfig:
        s3OutputPath: https://<AWS region>.amazonaws.com/<S3 bucket>/<output_path> # add your S3 bucket and region
    resourceConfig:
        instanceCount: 1
        instanceType: ml.p3.16xlarge
        volumeSizeInGB: 100
    stoppingCondition:
        maxRuntimeInSeconds: 216000
    inputDataConfig:
        - channelName: training
          dataSource:
            s3DataSource:
                s3DataType: S3Prefix
                s3Uri: https://<AWS region>.amazonaws.com/<S3 bucket>/<data_path> # add your S3 bucket and region
                s3DataDistributionType: FullyReplicated
          recordWrapperType: None
          compressionType: None